# Generated by Django 5.2.6 on 2025-09-11 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('face_ref', models.CharField(blank=True, max_length=120, null=True)),
                ('es_activo', models.BooleanField()),
                ('passwor', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id_camara', models.BigAutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=160)),
                ('estado', models.TextField()),
                ('tipo', models.CharField(blank=True, max_length=40, null=True)),
                ('rtsp_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'camara',
            },
        ),
        migrations.CreateModel(
            name='EspacioComun',
            fields=[
                ('id_espacio', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'espacio_comun',
            },
        ),
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id_cuota', models.BigAutoField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
            ],
            options={
                'db_table': 'mensualidad',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='personas.persona')),
                ('id_cargo', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id_persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='personas.persona')),
            ],
            options={
                'db_table': 'inquilino',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id_persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='personas.persona')),
            ],
            options={
                'db_table': 'propietario',
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('accion', models.CharField(max_length=160)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('id_persona', models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.persona')),
            ],
            options={
                'db_table': 'bitacora',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.TextField()),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('id_cuota', models.ForeignKey(db_column='id_cuota', on_delete=django.db.models.deletion.DO_NOTHING, to='personas.mensualidad')),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, to='personas.persona')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id_detalle', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_pago', models.ForeignKey(db_column='id_pago', on_delete=django.db.models.deletion.DO_NOTHING, to='personas.pago')),
            ],
            options={
                'db_table': 'detalle_pago',
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id_propiedad', models.BigAutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=160)),
                ('pertenece_a', models.CharField(max_length=12)),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, to='personas.persona')),
            ],
            options={
                'db_table': 'propiedad',
            },
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='id_propiedad',
            field=models.ForeignKey(db_column='id_propiedad', on_delete=django.db.models.deletion.DO_NOTHING, to='personas.propiedad'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('id_espacio', models.ForeignKey(db_column='id_espacio', on_delete=django.db.models.deletion.DO_NOTHING, to='personas.espaciocomun')),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, to='personas.persona')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=40, null=True)),
                ('modelo', models.CharField(blank=True, max_length=40, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, to='personas.persona')),
            ],
            options={
                'db_table': 'vehiculo',
            },
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id_acceso', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
                ('foto_url', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('hora_entrada', models.DateTimeField(blank=True, null=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('id_camara', models.ForeignKey(blank=True, db_column='id_camara', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.camara')),
                ('id_persona', models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.persona')),
                ('placa', models.ForeignKey(blank=True, db_column='placa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.vehiculo')),
            ],
            options={
                'db_table': 'registro_acceso',
            },
        ),
        migrations.CreateModel(
            name='AlertaIa',
            fields=[
                ('id_alerta', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
                ('detalle', models.TextField(blank=True, null=True)),
                ('foto_url', models.TextField(blank=True, null=True)),
                ('nivel_riesgo', models.IntegerField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField()),
                ('procesado', models.BooleanField()),
                ('id_persona', models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.persona')),
                ('id_camara', models.ForeignKey(blank=True, db_column='id_camara', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.camara')),
                ('placa', models.ForeignKey(blank=True, db_column='placa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.vehiculo')),
            ],
            options={
                'db_table': 'alerta_ia',
            },
        ),
        migrations.CreateModel(
            name='PropiedadPropietario',
            fields=[
                ('pk', models.CompositePrimaryKey('id_propiedad', 'id_persona', 'desde', blank=True, editable=False, primary_key=True, serialize=False)),
                ('desde', models.DateField()),
                ('hasta', models.DateField(blank=True, null=True)),
                ('id_propiedad', models.ForeignKey(db_column='id_propiedad', on_delete=django.db.models.deletion.DO_NOTHING, to='personas.propiedad')),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, to='personas.propietario')),
            ],
            options={
                'db_table': 'propiedad_propietario',
            },
        ),
        migrations.AlterUniqueTogether(
            name='mensualidad',
            unique_together={('id_propiedad', 'mes', 'anio')},
        ),
    ]
