# Generated by Django 5.2.6 on 2025-09-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('residente', 'Residente')], default='residente', max_length=20),
        ),
    ]
