# Generated by Django 5.2.6 on 2025-09-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_alter_pago_id_cuota_infraccion_pago_id_infraccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='reset_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='reset_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
