# Generated by Django 5.2.6 on 2025-09-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_bitacora_ip_aviso'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensualidad',
            name='estado',
            field=models.CharField(default='pendiente', max_length=50),
        ),
    ]
