# Generated by Django 5.2.6 on 2025-09-06 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('face_ref', models.CharField(blank=True, max_length=120, null=True)),
                ('es_activo', models.BooleanField()),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlertaIa',
            fields=[
                ('id_alerta', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
                ('detalle', models.TextField(blank=True, null=True)),
                ('foto_url', models.TextField(blank=True, null=True)),
                ('nivel_riesgo', models.IntegerField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField()),
                ('procesado', models.BooleanField()),
            ],
            options={
                'db_table': 'alerta_ia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('accion', models.CharField(max_length=160)),
                ('detalle', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bitacora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id_camara', models.BigAutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=160)),
                ('estado', models.TextField()),
                ('tipo', models.CharField(blank=True, max_length=40, null=True)),
                ('rtsp_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'camara',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id_detalle', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'detalle_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EspacioComun',
            fields=[
                ('id_espacio', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'espacio_comun',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id_cuota', models.BigAutoField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
            ],
            options={
                'db_table': 'mensualidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.TextField()),
                ('anio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id_propiedad', models.BigAutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=160)),
                ('pertenece_a', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'propiedad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropiedadPropietario',
            fields=[
                ('pk', models.CompositePrimaryKey('id_propiedad', 'id_persona', 'desde', blank=True, editable=False, primary_key=True, serialize=False)),
                ('desde', models.DateField()),
                ('hasta', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'propiedad_propietario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id_acceso', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
                ('foto_url', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('hora_entrada', models.DateTimeField(blank=True, null=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registro_acceso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=40, null=True)),
                ('modelo', models.CharField(blank=True, max_length=40, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'vehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='personas.persona')),
                ('id_cargo', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id_persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='personas.persona')),
            ],
            options={
                'db_table': 'inquilino',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id_persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='personas.persona')),
            ],
            options={
                'db_table': 'propietario',
                'managed': False,
            },
        ),
    ]
