# Generated by Django 5.2.6 on 2025-09-20 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_persona_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privilegio',
            fields=[
                ('id_persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='personas.persona')),
                ('corte_cesped', models.BooleanField(default=False)),
                ('entrada_auto', models.BooleanField(default=False)),
                ('recojo_basura', models.BooleanField(default=False)),
                ('avisos_visita', models.BooleanField(default=False)),
                ('acceso_gimnasio', models.BooleanField(default=False)),
                ('acceso_piscina', models.BooleanField(default=False)),
                ('acceso_sala_eventos', models.BooleanField(default=False)),
                ('permisos_especiales', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'privilegio',
            },
        ),
    ]
