# Generated by Django 5.2.6 on 2025-09-21 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_privilegio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='id_cuota',
            field=models.ForeignKey(blank=True, db_column='id_cuota', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.mensualidad'),
        ),
        migrations.CreateModel(
            name='Infraccion',
            fields=[
                ('id_infraccion', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, to='personas.persona')),
            ],
            options={
                'db_table': 'infraccion',
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='id_infraccion',
            field=models.ForeignKey(blank=True, db_column='id_infraccion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.infraccion'),
        ),
    ]
